build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u image-registry -p BbyB8HzkuysvipmJwFbT $CI_REGISTRY
    - docker build -t $CI_REGISTRY/redakcny_system_be:latest .
    - docker push $CI_REGISTRY/redakcny_system_be:latest
