build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u image-registry -p BbyB8HzkuysvipmJwFbT $CI_REGISTRY
    - docker build -t git.kpi.fei.tuke.sk:4567/kpi-zp/2022/dp.pavol.dlugos/redakcny_system_be:latest .
    - docker push git.kpi.fei.tuke.sk:4567/kpi-zp/2022/dp.pavol.dlugos/redakcny_system_be:latest
