version: '3.0'

services:
  backend:
    build: .
    environment:
      LOGIN_SUCCESS_CALLBACK_URL: 'http://localhost/api/login-callback'
      GITLAB_OAUTH_CLIENT_ID: 'afef94df75f368edbb735303e7b8fa5c7141131aed8239126055dabba80acc8c'
      GITLAB_OAUTH_CLIENT_SECRET: 'be993a6796915485219d444ad470d35cb3447463e4e8a57c9dc4979b1340bed3' 
      GITHUB_OAUTH_CLIENT_ID: 'Iv1.7f311c1dd843f6fb' 
      GITHUB_OAUTH_CLIENT_SECRET: '02c2e04b9e24f1a65794db909597dfe67d165f53'
      JWT_GENERATOR_SIGNATURE_SECRET: 'E)H@McQfTjWnZr4u7x!z%C*F-JaNdRgU'
      FRONTEND_URL: 'http://localhost'
      BACKEND_URL: 'api'
#     DOCKER POSTGRES DATABASE
      DATABASE_URL: 'jdbc:postgresql://db/redakcny_system'
      DATABASE_USERNAME: 'redakcny_system'
      DATABASE_PASSWORD: 'some-password'

#     ELEPHANT SERVICE POSTGRES
#      DATABASE_URL: 'jdbc:postgresql://surus.db.elephantsql.com/nyukudxs'
#      DATABASE_USERNAME: 'nyukudxs'
#      DATABASE_PASSWORD: 'z7Ss2VLr1qZ3wnG9K300nuiXhpUYVVrE'
  frontend:
    build: ../redakcny-system-fe
    ports:
      - "80:80"
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: "some-password"
      POSTGRES_USER: "redakcny_system"
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
